# Generated by Django 4.2.11 on 2024-05-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
