# Generated by Django 4.2.11 on 2024-05-18 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_client_team_access'),
        ('client', '0004_rename_prospectiveclient_comment_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий для клиента', 'verbose_name_plural': 'Коментарии для клиентов'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lients_comments', to='team.team', verbose_name='Команда клиента'),
        ),
    ]
