# Generated by Django 4.2.11 on 2024-05-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0004_alter_team_client_team_access'),
        ('client', '0005_alter_comment_options_alter_comment_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clients_files', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='client.client', verbose_name='Для кого оставлен файл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_files', to=settings.AUTH_USER_MODEL, verbose_name='Загружено кем')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_files', to='team.team', verbose_name='Команда клиента')),
            ],
            options={
                'verbose_name': 'Файл для клиента',
                'verbose_name_plural': 'Файлы для клиентов',
                'db_table': 'client_files',
            },
        ),
    ]
