# Generated by Django 4.2.11 on 2024-05-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTeamAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_prospective_clients', models.IntegerField()),
                ('max_clients', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Доступ к клиенту',
                'verbose_name_plural': 'Доступ к клиентам',
                'db_table': 'client_team_access',
            },
        ),
    ]
