# Generated by Django 4.2.11 on 2024-05-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_clientteamaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='client_team_access',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team.clientteamaccess'),
            preserve_default=False,
        ),
    ]
