# Generated by Django 4.2.11 on 2024-05-05 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectiveClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Новый клиент', 'Новый клиент'), ('Уже связались', 'Уже связались'), ('Назначен', 'Назначен'), ('Упущен', 'Упущен')], default='Новый клиент', max_length=45)),
                ('priority', models.CharField(choices=[('Низкий приоритет', 'Низкий приоритет'), ('Средний приоритет', 'Средний приоритет'), ('Высокий приоритет', 'Высокий приоритет')], default='Средний приоритет', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectiveclients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Потенциальный клиент',
                'verbose_name_plural': 'Потенциальные клиенты',
                'db_table': 'prospective_client',
            },
        ),
    ]
