# Generated by Django 4.2.11 on 2024-05-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospectiveclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospectiveclient',
            options={'ordering': ('name',), 'verbose_name': 'Потенциальный клиент', 'verbose_name_plural': 'Потенциальные клиенты'},
        ),
    ]
