# Generated by Django 4.2.11 on 2024-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectiveclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectiveclient',
            name='status',
            field=models.CharField(choices=[('Новый клиент', 'Новый клиент'), ('Уже связались', 'Уже связались'), ('В работе', 'В работе'), ('Упущен', 'Упущен')], default='Новый клиент', max_length=45),
        ),
    ]
