# Generated by Django 4.2.11 on 2024-05-06 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospectiveclient', '0002_alter_prospectiveclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectiveclient',
            name='converted_to_client',
            field=models.BooleanField(default=False, verbose_name='Стал клиентом'),
        ),
        migrations.AlterField(
            model_name='prospectiveclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано в'),
        ),
        migrations.AlterField(
            model_name='prospectiveclient',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Создано кем'),
        ),
        migrations.AlterField(
            model_name='prospectiveclient',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='prospectiveclient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='prospectiveclient',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено в'),
        ),
        migrations.AlterField(
            model_name='prospectiveclient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='prospectiveclient',
            name='priority',
            field=models.CharField(choices=[('Низкий приоритет', 'Низкий приоритет'), ('Средний приоритет', 'Средний приоритет'), ('Высокий приоритет', 'Высокий приоритет')], default='Средний приоритет', max_length=45, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='prospectiveclient',
            name='status',
            field=models.CharField(choices=[('Новый клиент', 'Новый клиент'), ('Уже связались', 'Уже связались'), ('В работе', 'В работе'), ('Упущен', 'Упущен')], default='Новый клиент', max_length=45, verbose_name='Статус'),
        ),
    ]
