# Generated by Django 4.2.11 on 2024-05-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospectiveclient', '0004_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='prospectiveclient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prospectiveclient.prospectiveclient', verbose_name='Для кого оставлен комментарий'),
        ),
    ]
