# Generated by Django 4.2.11 on 2024-05-18 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0004_alter_team_client_team_access'),
        ('prospectiveclient', '0005_alter_comment_prospectiveclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectiveclients_comments', to='team.team', verbose_name='Команда потенциального клиента'),
        ),
        migrations.CreateModel(
            name='ProspectiveClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prospective_clients_files', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectiveclients_files', to=settings.AUTH_USER_MODEL, verbose_name='Загружено кем')),
                ('prospectiveclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='prospectiveclient.prospectiveclient', verbose_name='Для кого оставлен файл')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectiveclients_files', to='team.team', verbose_name='Команда потенциального клиента')),
            ],
            options={
                'verbose_name': 'Файл для потенциального клиента',
                'verbose_name_plural': 'Файлы для потенциальных клиентов',
                'db_table': 'prospective_client_files',
            },
        ),
    ]
